url: https://www.ashwinvaswani.github.io
baseurl: /new-website/

# Site settings
title: Welcome!
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Members names, titles and social links
people:
- name: Pranav Garg
  pic: alish
  position: GOD
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Alish Dipani
  pic: alish
  position: GOD2
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sharad Hitlangia
  pic: alish
  position: GOD3
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Mehul Rastogi
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rijul Ganguly
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Ashwin Vaswani
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


- name: Het Shah
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


- name: Rajaswa Patil
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


- name: Ajay Subramanium
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Aditya Ahuja
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Sauradeep Chakravarthy
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Shangeth
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Pranav Mahajan
  pic: alish
  position: GOD4
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: https://github.com/SforAiDl

# Postal address (add as many lines as necessary)
address:
  - line: BITS Pilani
  - line: K K Birla Goa Campus

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman
